//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.assigmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int department_no { get; set; }
        public string department_name { get; set; }
        public int emp_no { get; set; }
        public int employe_experience { get; set; }
    
        public virtual experience experience { get; set; }
        public virtual employee employee { get; set; }
    }
}
