//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT.assigmnt
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int emp_no { get; set; }
        public Nullable<int> salary1 { get; set; }
        public string from_date { get; set; }
        public string to_date { get; set; }
    }
}
